 export const PLACEHOLDER_IMAGE = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mOcbAwAAV8AyAwNLCsAAAAASUVORK5CYII="
 export const WITH_IMAGE = 170
 export const HEIGHT_IMAGE = 170
 export const HEIGHT_IMAGE_SUMMARY = 270
 export const WITH_IMAGE_SUMMARY = 270